sudo: false
dist: trusty
language: python
before_install:
- pip install awscli
jobs:
  include:
  - stage: Setting AWS configure, build and push nginxtest docker image to aws ecr
    script:
    - eval $(aws ecr get-login --no-include-email)
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/godway/$REPO_NAME:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/godway/$REPO_NAME:latest
    - aws ecs register-task-definition --cli-input-json file://task-definition.json
    - aws ecs update-service --cluster FirstCluster --service first-service --task-definition web
