sudo: false
dist: trusty
language: python
before_install:
- pip install awscli
jobs:
  include:
  - stage: Setting AWS configure, build and push nginxtest docker image to aws ecr
    script:
    - eval $(aws ecr get-login --no-include-email)
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/godway/$REPO_NAME:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/godway/$REPO_NAME:latest
  notifications:
    slack:
      on_pull_requests: true
      rooms:
      on_success: always
      on_failure: always
